// eslint-disable-next-line import/prefer-default-export
export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  GET_USERDATA: "GET_USERDATA",
  GET_USERDATA_REFRESH: "GET_USERDATA_REFRESH",
};
export const programConstansts = {
  GET_ALL_PROGRAMS_SUCCESS: "GET_ALL_PROGRAMS_SUCCESS",
  GET_ALL_PROGRAMS_FAILURE: "GET_ALL_PROGRAMS_FAILURE",
  ADD_NEW_PROGRAM_REQUEST: "ADD_NEW_PROGRAM_REQUEST",
  ADD_NEW_PROGRAM_SUCCESS: "ADD_NEW_PROGRAM_SUCCESS",
  ADD_NEW_PROGRAM_FAILURE: "ADD_NEW_PROGRAM_FAILURE",
  UPDATE_PROGRAM_REQUEST: "UPDATE_PROGRAM_REQUEST",
  UPDATE_PROGRAM_SUCCESS: "UPDATE_PROGRAM_SUCCESS",
  UPDATE_PROGRAM_FAILURE: "UPDATE_PROGRAM_FAILURE",
  DELETE_PROGRAM_REQUEST: "DELETE_PROGRAM_REQUEST",
  DELETE_PROGRAM_SUCCESS: "DELETE_PROGRAM_SUCCESS",
  DELETE_PROGRAM_FAILURE: "DELETE_PROGRAM_FAILURE",
};
export const courseConstansts = {
  GET_ALL_COURSES_SUCCESS: "GET_ALL_COURSES_SUCCESS",
  GET_ALL_COURSES_FAILURE: "GET_ALL_COURSES_FAILURE",
  ADD_NEW_COURSE_REQUEST: "ADD_NEW_COURSE_REQUEST",
  ADD_NEW_COURSE_SUCCESS: "ADD_NEW_COURSE_SUCCESS",
  ADD_NEW_COURSE_FAILURE: "ADD_NEW_COURSE_FAILURE",
  UPDATE_COURSE_REQUEST: "UPDATE_COURSE_REQUEST",
  UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
  UPDATE_COURSE_FAILURE: "UPDATE_COURSE_FAILURE",
  DELETE_COURSE_REQUEST: "DELETE_COURSE_REQUEST",
  DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
  DELETE_COURSE_FAILURE: "DELETE_COURSE_FAILURE",
};
export const subcategoryConstansts = {
  GET_ALL_SUBCATEGORIES_SUCCESS: "GET_ALL_SUBCATEGORIES_SUCCESS",
  GET_ALL_SUBCATEGORIES_FAILURE: "GET_ALL_SUBCATEGORIES_FAILURE",
  ADD_NEW_SUBCATEGORY_REQUEST: "ADD_NEW_SUBCATEGORY_REQUEST",
  ADD_NEW_SUBCATEGORY_SUCCESS: "ADD_NEW_SUBCATEGORY_SUCCESS",
  ADD_NEW_SUBCATEGORY_FAILURE: "ADD_NEW_SUBCATEGORY_FAILURE",
  UPDATE_SUBCATEGORY_REQUEST: "UPDATE_SUBCATEGORY_REQUEST",
  UPDATE_SUBCATEGORY_SUCCESS: "UPDATE_SUBCATEGORY_SUCCESS",
  UPDATE_SUBCATEGORY_FAILURE: "UPDATE_SUBCATEGORY_FAILURE",
  DELETE_SUBCATEGORY_REQUEST: "DELETE_SUBCATEGORY_REQUEST",
  DELETE_SUBCATEGORY_SUCCESS: "DELETE_SUBCATEGORY_SUCCESS",
  DELETE_SUBCATEGORY_FAILURE: "DELETE_SUBCATEGORY_FAILURE",
};
export const subjectConstansts = {
  GET_ALL_SUBJECTS_SUCCESS: "GET_ALL_SUBJECTS_SUCCESS",
  GET_ALL_SUBJECTS_FAILURE: "GET_ALL_SUBJECTS_FAILURE",
  ADD_NEW_SUBJECT_REQUEST: "ADD_NEW_SUBJECT_REQUEST",
  ADD_NEW_SUBJECT_SUCCESS: "ADD_NEW_SUBJECT_SUCCESS",
  ADD_NEW_SUBJECT_FAILURE: "ADD_NEW_SUBJECT_FAILURE",
  UPDATE_SUBJECT_REQUEST: "UPDATE_SUBJECT_REQUEST",
  UPDATE_SUBJECT_SUCCESS: "UPDATE_SUBJECT_SUCCESS",
  UPDATE_SUBJECT_FAILURE: "UPDATE_SUBJECT_FAILURE",
  DELETE_SUBJECT_REQUEST: "DELETE_SUBJECT_REQUEST",
  DELETE_SUBJECT_SUCCESS: "DELETE_SUBJECT_SUCCESS",
  DELETE_SUBJECT_FAILURE: "DELETE_SUBJECT_FAILURE",
};
export const semesterConstansts = {
  GET_ALL_SEMESTERS_SUCCESS: "GET_ALL_SEMESTERS_SUCCESS",
  GET_ALL_SEMESTERS_FAILURE: "GET_ALL_SEMESTERS_FAILURE",
  ADD_NEW_SEMESTER_REQUEST: "ADD_NEW_SEMESTER_REQUEST",
  ADD_NEW_SEMESTER_SUCCESS: "ADD_NEW_SEMESTER_SUCCESS",
  ADD_NEW_SEMESTER_FAILURE: "ADD_NEW_SEMESTER_FAILURE",
  UPDATE_SEMESTER_REQUEST: "UPDATE_SEMESTER_REQUEST",
  UPDATE_SEMESTER_SUCCESS: "UPDATE_SEMESTER_SUCCESS",
  UPDATE_SEMESTER_FAILURE: "UPDATE_SEMESTER_FAILURE",
  DELETE_SEMESTER_REQUEST: "DELETE_SEMESTER_REQUEST",
  DELETE_SEMESTER_SUCCESS: "DELETE_SEMESTER_SUCCESS",
  DELETE_SEMESTER_FAILURE: "DELETE_SEMESTER_FAILURE",
};
export const subSubcategoryConstansts = {
  GET_ALL_SUBSUBCATEGORYLINKS_SUCCESS: "GET_ALL_SUBSUBCATEGORYLINKS_SUCCESS",
  GET_ALL_SUBSUBCATEGORYLINKS_FAILURE: "GET_ALL_SUBSUBCATEGORYLINKS_FAILURE",
  ADD_NEW_SUBSUBCATEGORYLINK_REQUEST: "ADD_NEW_SUBSUBCATEGORYLINK_REQUEST",
  ADD_NEW_SUBSUBCATEGORYLINK_SUCCESS: "ADD_NEW_SUBSUBCATEGORYLINK_SUCCESS",
  ADD_NEW_SUBSUBCATEGORYLINK_FAILURE: "ADD_NEW_SUBSUBCATEGORYLINK_FAILURE",
};
export const subcategoryCourseConstansts = {
  GET_ALL_SUBCATEGORYCOURSELINKS_SUCCESS: "GET_ALL_SUBCATEGORYCOURSELINKS_SUCCESS",
  GET_ALL_SUBCATEGORYCOURSELINKS_FAILURE: "GET_ALL_SUBCATEGORYCOURSELINKS_FAILURE",
  ADD_NEW_SUBCATEGORYCOURSELINK_REQUEST: "ADD_NEW_SUBCATEGORYCOURSELINK_REQUEST",
  ADD_NEW_SUBCATEGORYCOURSELINK_SUCCESS: "ADD_NEW_SUBCATEGORYCOURSELINK_SUCCESS",
  ADD_NEW_SUBCATEGORYCOURSELINK_FAILURE: "ADD_NEW_SUBCATEGORYCOURSELINK_FAILURE",
};
export const programCourseConstansts = {
  GET_ALL_PROGRAMCOURSELINKS_SUCCESS: "GET_ALL_PROGRAMCOURSELINKS_SUCCESS",
  GET_ALL_PROGRAMCOURSELINKS_FAILURE: "GET_ALL_PROGRAMCOURSELINKS_FAILURE",
  ADD_NEW_PROGRAMCOURSELINK_REQUEST: "ADD_NEW_PROGRAMCOURSELINK_REQUEST",
  ADD_NEW_PROGRAMCOURSELINK_SUCCESS: "ADD_NEW_PROGRAMCOURSELINK_SUCCESS",
  ADD_NEW_PROGRAMCOURSELINK_FAILURE: "ADD_NEW_PROGRAMCOURSELINK_FAILURE",
};
