// eslint-disable-next-line import/prefer-default-export
export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  GET_USERDATA: "GET_USERDATA",
  GET_USERDATA_REFRESH: "GET_USERDATA_REFRESH",
};
